# SQL-EX with Postgres

## Импорты и подготовки

In [89]:
# Install postgresql server
!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql
!sudo service postgresql start

# Setup a password `postgres` for username `postgres`
!sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD 'postgres';"

 * Starting PostgreSQL 10 database server
   ...done.
ALTER ROLE


In [90]:
from sqlalchemy import create_engine
con = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/postgres')

Сохранение БД с sql-ex

In [91]:
!wget https://sql-ex.ru/download/sql-ex-pg.sql

--2022-01-10 16:57:34--  https://sql-ex.ru/download/sql-ex-pg.sql
Resolving sql-ex.ru (sql-ex.ru)... 136.243.105.254, 2a01:4f8:171:ed3:ce0:a1ff:fee0:bb42
Connecting to sql-ex.ru (sql-ex.ru)|136.243.105.254|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41053 (40K) [application/x-sql]
Saving to: ‘sql-ex-pg.sql.1’

sql-ex-pg.sql.1     100%[===================>]  40.09K  --.-KB/s    in 0s      

2022-01-10 16:57:34 (188 MB/s) - ‘sql-ex-pg.sql.1’ saved [41053/41053]



In [92]:
with open('/content/sql-ex-pg.sql', 'r') as file:
    sql = file.read()

Запускаем скрипт

In [93]:
con.execute(sql[1:])

Функция для запуска селекта

In [94]:
import pandas as pd

In [95]:
def select(sql):
  return pd.read_sql(sql,con)

## Задачи 1-10

### Задача 1

Найдите номер модели, скорость и размер жесткого диска для всех ПК стоимостью менее 500 дол. Вывести: model, speed и hd

In [96]:
sql = '''
select t.model, t.speed, t.hd
from PC t
where t.price < 500
'''
select (sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

### Задача 2

Найдите производителей принтеров. Вывести: maker

In [97]:
sql = '''
select 
distinct t.maker
from product t
where t.type = 'Printer'
'''
select (sql)

maker
0     A
1     D
2     E

### Задача 3

Найдите номер модели, объем памяти и размеры экранов ПК-блокнотов, цена которых превышает 1000 дол.

In [98]:
sql = '''
select t.model, t.ram, t.screen
from laptop t
where t.price > 1000
'''
select (sql)

model  ram  screen
0  1750  128      14
1  1298   64      15
2  1752  128      14

### Задача 4

Найдите все записи таблицы Printer для цветных принтеров.

In [99]:
sql = '''
select p.* 
from Printer p
where p.color = 'y'
'''
select (sql)

code model color type  price
0     2  1433     y  Jet  270.0
1     3  1434     y  Jet  290.0

### Задача 5

Найдите номер модели, скорость и размер жесткого диска ПК, имеющих 12x или 24x CD и цену менее 600 дол.

In [100]:
sql = '''
select pc.model, pc.speed, pc.hd
from pc 
where pc.cd in ('12x','24x') and pc.price < 600
'''
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

### Задача 6

Для каждого производителя, выпускающего ПК-блокноты c объёмом жесткого диска не менее 10 Гбайт, найти скорости таких ПК-блокнотов. Вывод: производитель, скорость.

In [101]:
sql = '''
select 
distinct p.maker, l.speed
from product p
join laptop l on l.model = p.model
where l.hd >= 10
'''
select (sql)

maker  speed
0     A    750
1     A    450
2     A    600
3     B    750

### Задача 7

Найдите номера моделей и цены всех имеющихся в продаже продуктов (любого типа) производителя B (латинская буква).

In [102]:
sql = ''' 
  select pr.model from product pr
  where pr.maker = 'B'
  '''
select (sql)

model
0  1121
1  1750

In [103]:
sql = ''' 
with products as (
  select pc.model, pc.price
  from pc
  union 
  select l.model, l.price
  from laptop l
  union 
  select pr.model, pr.price
  from printer pr
)
select p.*
from products p
where p.model in (
  select pr.model from product pr
  where pr.maker = 'B'
)
'''
select (sql)

model   price
0  1121   850.0
1  1750  1200.0

### Задача 8

Найдите производителя, выпускающего ПК, но не ПК-блокноты.

In [104]:
sql = '''
select p.maker from product p where type = 'PC'
except
select p.maker from product p where type = 'Laptop'
'''
select (sql)

maker
0     E

### Задача 9

Найдите производителей ПК с процессором не менее 450 Мгц. Вывести: Maker

In [105]:
sql = '''
select distinct pr.maker
from product pr
join pc on pc.model = pr.model
where pc.speed >= 450
'''
select (sql)

maker
0     B
1     E
2     A

### Задача 10

Найдите модели принтеров, имеющих самую высокую цену. Вывести: model, price

In [106]:
sql = '''
select p.model, p.price
from printer p
where p.price in (
  select max (price) from printer
)
'''
select(sql)

model  price
0  1276  400.0
1  1288  400.0

## Задачи 11 -20

### Задача 11

Найдите среднюю скорость ПК.

In [107]:
sql = '''
select avg(pc.speed) from pc
''' 
select (sql)

avg
0  608.333333

### Задача 12

Найдите среднюю скорость ПК-блокнотов, цена которых превышает 1000 дол.

In [108]:
sql = '''
select avg(l.speed) 
from laptop l
where l.price > 1000
'''
select(sql)

avg
0  700.0

### Задача 13

Найдите среднюю скорость ПК, выпущенных производителем A.

In [109]:
sql = '''
select  avg(pc.speed)
from pc
join product p on p.model = pc.model
where (p.maker = 'A')
'''
select(sql)

avg
0  606.25

### Задача 14

Найдите класс, имя и страну для кораблей из таблицы Ships, имеющих не менее 10 орудий.

In [110]:
sql = '''
select c.class, s.name, c.country
from ships s
join classes c on s.class = c.class
where c.numguns >= 10
'''
select(sql)

class            name country
0       Tennessee      California     USA
1  North Carolina  North Carolina     USA
2       Tennessee       Tennessee     USA
3  North Carolina      Washington     USA
4  North Carolina    South Dakota     USA

### Задача 15

Найдите размеры жестких дисков, совпадающих у двух и более PC. Вывести: HD

In [111]:
sql = '''
select pc.hd
from pc
group by pc.hd
having count(1) >= 2
'''
select(sql)

hd
0   8.0
1  20.0
2   5.0
3  14.0
4  10.0

### Задача 16

Найдите пары моделей PC, имеющих одинаковые скорость и RAM. В результате каждая пара указывается только один раз, т.е. (i,j), но не (j,i), Порядок вывода: модель с большим номером, модель с меньшим номером, скорость и RAM.

In [112]:
sql = '''
select distinct a.model, b.model,
a.speed, b.ram
from pc a, pc b
where (a.model > b.model) and (a.speed = b.speed) and (b.ram = a.ram)
'''
select(sql)

model model  speed  ram
0  1233  1121    750  128
1  1233  1232    500   64
2  1260  1232    500   32

### Задача 17

Найдите модели ПК-блокнотов, скорость которых меньше скорости каждого из ПК.
Вывести: type, model, speed

In [113]:
sql = '''
select distinct p.type, l.model, l.speed
from laptop l
join product p on p.model = l.model
where l.speed < ALL (select pc.speed from pc )
'''
select(sql)

type model  speed
0  Laptop  1298    350

### Задача 18

Найдите производителей самых дешевых цветных принтеров. Вывести: maker, price

In [114]:
sql = '''
with color_pr as (
  select p.maker, pr.price
  from printer pr 
  join product p on p.model = pr.model
  where (pr.color = 'y')
)
select distinct cpr.maker, cpr.price
from color_pr cpr
where cpr.price in (select min (cpr.price) from color_pr cpr)
'''
select(sql)

maker  price
0     D  270.0

### Задача 19

Для каждого производителя, имеющего модели в таблице Laptop, найдите средний размер экрана выпускаемых им ПК-блокнотов.
Вывести: maker, средний размер экрана.

In [115]:
sql = '''
select p.maker, avg (l.screen)
from product p
join laptop l on l.model = p.model
group by p.maker
'''
select(sql)

maker   avg
0     B  14.0
1     C  12.0
2     A  13.0

### Задача 20

Найдите производителей, выпускающих по меньшей мере три различных модели ПК. Вывести: Maker, число моделей ПК.

In [116]:
sql = '''
select p.maker, count (p.model) as cnt 
from product p
where p.type = 'PC'
group by p.maker
having count (p.model) >= 3
'''
select(sql)

maker  cnt
0     E    3

## Задачи 21 - 30 

### Задача 21

Найдите максимальную цену ПК, выпускаемых каждым производителем, у которого есть модели в таблице PC.
Вывести: maker, максимальная цена.

In [117]:
sql = '''
select p.maker as maker, max (pc.price) as max_price
from product p
join pc on pc.model = p.model
group by p.maker
'''
select(sql)

maker  max_price
0     B      850.0
1     E      350.0
2     A      980.0

### Задача 22

Для каждого значения скорости ПК, превышающего 600 МГц, определите среднюю цену ПК с такой же скоростью. Вывести: speed, средняя цена.

In [118]:
sql = '''
select pc.speed, avg (pc.price) as price_avg
from pc
where pc.speed > 600
group by pc.speed
'''
select(sql)

speed  price_avg
0    900      980.0
1    750      900.0
2    800      970.0

### Задача 23

Найдите производителей, которые производили бы как ПК
со скоростью не менее 750 МГц, так и ПК-блокноты со скоростью не менее 750 МГц.
Вывести: Maker

In [119]:
sql = '''
select p.maker
from product p 
join pc on pc.model = p.model
where pc.speed >= 750

intersect

select p.maker
from product p 
join laptop l on l.model = p.model
where l.speed >= 750
'''
select(sql)

maker
0     B
1     A

In [120]:
sql = '''
SELECT p.maker
FROM product p JOIN (
select maker 
From product
where model in (select model from laptop where speed >=750)
) A on A.maker = p.maker
WHERE p.model in (select model from PC where speed >=750)
''' 
select (sql)

maker
0     B
1     A

### Задача 24

Перечислите номера моделей любых типов, имеющих самую высокую цену по всей имеющейся в базе данных продукции.

In [121]:
sql = '''
with table_price AS
(select model, price from pc
union
select model, price from laptop
union
select model, price from printer)

select distinct tp.model 
from table_price tp
where tp.price in (select max(price) from table_price)
'''
select(sql)

model
0  1750

### Задача 25

Найдите производителей принтеров, которые производят ПК с наименьшим объемом RAM и с самым быстрым процессором среди всех ПК, имеющих наименьший объем RAM. Вывести: Maker

In [122]:
#Определение рс с минимальной памятью
sql = '''
with min_ram_pc as(
  select pc.*
  from pc 
  where pc.ram in (select min (pc.ram) from pc)
)
select * from min_ram_pc
'''
select(sql)

code model  speed  ram    hd   cd  price
0     7  1232    500   32  10.0  12x  400.0
1     9  1232    450   32  10.0  24x  350.0
2    10  1260    500   32  10.0  12x  350.0

In [123]:
sql = '''
-- Производители принтеров
with printers as (
  select distinct p.maker 
  from product p
  where p.type = 'Printer'
),

-- Производители рс с мин памятью
min_ram_pc as(
  select pc.*
  from pc 
  where (pc.ram in (select min (pc.ram) from pc))
),

-- Производители рс с мин памятью и макс.скоростью
max_speed_pc as (
  select mrpc.model
  from min_ram_pc mrpc
  where mrpc.speed in (select max(mrpc.speed) from min_ram_pc mrpc)
)

-- Пересечение производителей

select pr.maker 
from printers pr

intersect

select p.maker
from product p 
join max_speed_pc ms on ms.model = p.model
'''
select(sql)

maker
0     A
1     E

### Задача 26

Найдите среднюю цену ПК и ПК-блокнотов, выпущенных производителем A (латинская буква). Вывести: одна общая средняя цена.

In [124]:
sql = '''
with a_makers as (
  select l.price
  from laptop l, product p
  where l.model = p.model and p.maker = 'A'
  
  union all

  select pc.price
  from pc, product p
  where pc.model = p.model and p.maker = 'A'
)

select avg (am.price) as avg_price
from a_makers am
'''
select(sql)

avg_price
0  754.166667

### Задача 27

Найдите средний размер диска ПК каждого из тех производителей, которые выпускают и принтеры. Вывести: maker, средний размер HD.

In [125]:
sql = '''
select p.maker, avg (pc.hd) as avg_hd
from product p
join pc on p.model = pc.model
where  p.maker IN (select p.maker from product p where p.type = 'Printer') 
group by (p.maker)
'''
select(sql)

maker  avg_hd
0     E   10.00
1     A   14.75

### Задача 28

Используя таблицу Product, определить количество производителей, выпускающих по одной модели.

In [126]:
sql = '''
with one_model as (
  select p.maker
  from product p
  group by p.maker
  having count (p.model)  = 1
)

select count (1) as cnt
from one_model om
'''
select(sql)

cnt
0    1

### Задача 29

В предположении, что приход и расход денег на каждом пункте приема фиксируется не чаще одного раза в день [т.е. первичный ключ (пункт, дата)], написать запрос с выходными данными (пункт, дата, приход, расход). Использовать таблицы Income_o и Outcome_o.

In [127]:
sql = '''
select i.point, i.date, i.inc, o.out
from Income_o i 
left join Outcome_o o ON (i.point = o.point AND i.date = o.date)

UNION

select o.point, o.date, i.inc, o.out
from outcome_o o 
left join income_o i ON (i.point = o.point AND i.date = o.date)
'''
select (sql)

point       date      inc       out
0       3 2001-09-14      NaN   2300.00
1       1 2001-04-11      NaN   3195.04
2       2 2001-03-22  10000.0   1440.00
3       3 2001-10-02  18000.0       NaN
4       1 2001-03-26      NaN   1221.00
5       1 2001-03-28      NaN   2075.00
6       2 2001-04-02      NaN   2040.00
7       2 2001-03-29      NaN   7848.00
8       1 2001-05-11   4500.0   2530.00
9       1 2001-03-29      NaN   2004.00
10      1 2001-04-27      NaN   3110.00
11      3 2002-09-16      NaN   2150.00
12      1 2001-04-13   5000.0   4490.00
13      1 2001-03-23  15000.0       NaN
14      1 2001-03-22  15000.0       NaN
15      2 2001-03-24   1500.0       NaN
16      1 2001-03-24   3400.0   3663.00
17      3 2001-09-13  11500.0   1500.00
18      1 2001-03-14      NaN  15348.00

### Задача 30

В предположении, что приход и расход денег на каждом пункте приема фиксируется произвольное число раз (первичным ключом в таблицах является столбец code), требуется получить таблицу, в которой каждому пункту за каждую дату выполнения операций будет соответствовать одна строка.
Вывод: point, date, суммарный расход пункта за день (out), суммарный приход пункта за день (inc). Отсутствующие значения считать неопределенными (NULL).

In [128]:
sql = '''
select * from income
limit 3
'''
select(sql)

code  point       date      inc
0     1      1 2001-03-22  15000.0
1     2      1 2001-03-23  15000.0
2     3      1 2001-03-24   3600.0

In [129]:
sql = '''
select * from outcome 
limit 3'''
select (sql)

code  point       date      out
0     1      1 2001-03-14  15348.0
1     2      1 2001-03-24   3663.0
2     3      1 2001-03-26   1221.0

In [130]:
sql = '''
select i.point, i.date, sum(i.inc) as inc, null outs 
from income i
group by i.point, i.date
'''
select (sql)

point       date      inc  outs
0      1 2001-03-24   7000.0  None
1      1 2001-05-11   4500.0  None
2      2 2001-03-24   3000.0  None
3      1 2001-03-23  15000.0  None
4      1 2001-03-22  30000.0  None
5      3 2001-09-13   3100.0  None
6      2 2001-03-22  10000.0  None
7      1 2001-04-13  10000.0  None

In [132]:
sql = '''
with sum_data as (
  select i.point, i.date, sum(i.inc) as inc, null outs 
  from income i
  group by i.point, i.date

  union 

  select o.point, o.date, null inc, sum (o.out) as outs
  from outcome o
  group by o.point, o.date
)

select sd.point, sd.date, sum (sd.outs) as out, sum (sd.inc) as inc
from sum_data sd
group by sd.point, sd.date
'''
select (sql)

point       date       out      inc
0       1 2001-03-24   7163.00   7000.0
1       1 2001-05-11   2530.00   4500.0
2       2 2001-03-24       NaN   3000.0
3       1 2001-04-11   3195.04      NaN
4       1 2001-03-23       NaN  15000.0
5       3 2001-09-14   1150.00      NaN
6       1 2001-03-22       NaN  30000.0
7       1 2001-03-26   1221.00      NaN
8       1 2001-03-29   4010.00      NaN
9       2 2001-04-02   2040.00      NaN
10      3 2001-09-13   2700.00   3100.0
11      1 2001-04-27   3110.00      NaN
12      1 2001-03-28   2075.00      NaN
13      1 2001-03-14  15348.00      NaN
14      2 2001-03-22   2880.00  10000.0
15      2 2001-03-29   7848.00      NaN
16      1 2001-04-13   4490.00  10000.0